import { NextResponse } from "next/server";
import { db } from "@/db";
import { users, subscriptions, listings } from "@/db/schema";
import { eq } from "drizzle-orm";
import { hashPassword } from "@/lib/auth";

export async function POST() {
  try {
    // Check if admin already exists
    const existing = await db
      .select()
      .from(users)
      .where(eq(users.email, "samuel.adesanya1love@gmail.com"))
      .limit(1);

    if (existing.length > 0) {
      return NextResponse.json({ message: "Data already seeded" });
    }

    const hashed = await hashPassword("admin123");

    // Create main admin - Samuel
    const [admin] = await db
      .insert(users)
      .values({
        email: "samuel.adesanya1love@gmail.com",
        password: hashed,
        name: "Samuel Adesanya",
        phone: "+237670000001",
        role: "admin",
        isActive: true,
      })
      .returning();

    await db.insert(subscriptions).values({
      userId: admin.id,
      isActive: true,
      startDate: new Date(),
      endDate: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000),
    });

    // Create demo agents
    const agentHash = await hashPassword("agent123");
    
    const demoAgents = [
      {
        email: "marie.nguema@gmail.com",
        name: "Marie Nguema",
        phone: "+237677123456",
      },
      {
        email: "jean.mballa@gmail.com",
        name: "Jean-Pierre Mballa",
        phone: "+237699876543",
      },
      {
        email: "fatima.bello@gmail.com",
        name: "Fatima Bello",
        phone: "+237655432100",
      },
      {
        email: "paul.etoga@gmail.com",
        name: "Paul Etoga",
        phone: "+237690111222",
      },
      {
        email: "sarah.kamga@gmail.com",
        name: "Sarah Kamga",
        phone: "+237678999888",
      },
    ];

    const createdAgents = [];
    for (const agent of demoAgents) {
      const [created] = await db
        .insert(users)
        .values({
          email: agent.email,
          password: agentHash,
          name: agent.name,
          phone: agent.phone,
          role: "agent",
          isActive: true,
        })
        .returning();

      await db.insert(subscriptions).values({
        userId: created.id,
        isActive: true,
        startDate: new Date(),
        endDate: new Date(Date.now() + 60 * 24 * 60 * 60 * 1000), // 60 days
      });

      createdAgents.push(created);
    }

    // Create sample listings with variety
    const sampleListings = [
      // Residential - Rent
      {
        userId: createdAgents[0].id,
        title: "Luxurious 4-Bedroom Villa with Pool in Bastos",
        description: "Exceptional villa in the prestigious Bastos neighborhood. Features include a private swimming pool, landscaped garden, modern kitchen, and 24/7 security. Perfect for diplomats or executives.",
        category: "residential" as const,
        listingType: "rent" as const,
        price: "1500000",
        city: "Yaoundé",
        area: "Bastos",
        bedrooms: 4,
        bathrooms: 3,
        isFurnished: true,
        hasParking: true,
        hasWater: true,
        hasElectricity: true,
        hasSecurity: true,
        hasWifi: true,
        images: [],
        agentName: createdAgents[0].name,
        agentPhone: createdAgents[0].phone || "",
        agentWhatsapp: createdAgents[0].phone || "",
        status: "approved" as const,
      },
      {
        userId: createdAgents[0].id,
        title: "Modern 3-Bedroom Apartment in Bonapriso",
        description: "Beautiful furnished apartment with stunning city views. Located in the heart of Bonapriso, close to restaurants, shops, and the business district. Recently renovated with high-end finishes.",
        category: "residential" as const,
        listingType: "rent" as const,
        price: "450000",
        city: "Douala",
        area: "Bonapriso",
        bedrooms: 3,
        bathrooms: 2,
        isFurnished: true,
        hasParking: true,
        hasWater: true,
        hasElectricity: true,
        hasSecurity: true,
        hasWifi: true,
        images: [],
        agentName: createdAgents[0].name,
        agentPhone: createdAgents[0].phone || "",
        agentWhatsapp: createdAgents[0].phone || "",
        status: "approved" as const,
      },
      {
        userId: createdAgents[1].id,
        title: "Cozy 2-Bedroom Apartment Near University",
        description: "Perfect for students or young professionals. This well-maintained apartment is just 5 minutes from the University of Douala. Includes water and electricity in rent.",
        category: "residential" as const,
        listingType: "rent" as const,
        price: "120000",
        city: "Douala",
        area: "Makepe",
        bedrooms: 2,
        bathrooms: 1,
        isFurnished: false,
        hasParking: false,
        hasWater: true,
        hasElectricity: true,
        hasSecurity: false,
        hasWifi: false,
        images: [],
        agentName: createdAgents[1].name,
        agentPhone: createdAgents[1].phone || "",
        agentWhatsapp: createdAgents[1].phone || "",
        status: "approved" as const,
      },
      {
        userId: createdAgents[1].id,
        title: "Spacious Studio in Akwa",
        description: "Bright and airy studio apartment in the commercial heart of Douala. Ideal for business travelers or singles. All amenities within walking distance.",
        category: "residential" as const,
        listingType: "rent" as const,
        price: "85000",
        city: "Douala",
        area: "Akwa",
        bedrooms: 1,
        bathrooms: 1,
        isFurnished: true,
        hasParking: false,
        hasWater: true,
        hasElectricity: true,
        hasSecurity: true,
        hasWifi: true,
        images: [],
        agentName: createdAgents[1].name,
        agentPhone: createdAgents[1].phone || "",
        agentWhatsapp: createdAgents[1].phone || "",
        status: "approved" as const,
      },
      // Residential - Sale
      {
        userId: createdAgents[2].id,
        title: "Executive 5-Bedroom House for Sale in Bastos",
        description: "Magnificent property in prime location. This architectural masterpiece features marble floors, a gourmet kitchen, home office, and a beautiful terrace overlooking the city.",
        category: "residential" as const,
        listingType: "sale" as const,
        price: "250000000",
        city: "Yaoundé",
        area: "Bastos",
        bedrooms: 5,
        bathrooms: 4,
        isFurnished: false,
        hasParking: true,
        hasWater: true,
        hasElectricity: true,
        hasSecurity: true,
        hasWifi: true,
        images: [],
        agentName: createdAgents[2].name,
        agentPhone: createdAgents[2].phone || "",
        agentWhatsapp: createdAgents[2].phone || "",
        status: "approved" as const,
      },
      {
        userId: createdAgents[2].id,
        title: "Brand New 3-Bedroom House in Kotto",
        description: "Newly constructed modern house with quality finishes. Open floor plan, equipped kitchen, and a nice backyard. Located in a quiet, family-friendly neighborhood.",
        category: "residential" as const,
        listingType: "sale" as const,
        price: "45000000",
        city: "Douala",
        area: "Kotto",
        bedrooms: 3,
        bathrooms: 2,
        isFurnished: false,
        hasParking: true,
        hasWater: true,
        hasElectricity: true,
        hasSecurity: false,
        hasWifi: false,
        images: [],
        agentName: createdAgents[2].name,
        agentPhone: createdAgents[2].phone || "",
        agentWhatsapp: createdAgents[2].phone || "",
        status: "approved" as const,
      },
      // Commercial
      {
        userId: createdAgents[3].id,
        title: "Prime Office Space in Bonanjo Business District",
        description: "Professional office space in the heart of Douala's business district. Open floor plan with conference room, reception area, and private offices. High-speed internet ready.",
        category: "commercial" as const,
        listingType: "lease" as const,
        price: "800000",
        city: "Douala",
        area: "Bonanjo",
        bedrooms: null,
        bathrooms: 2,
        isFurnished: false,
        hasParking: true,
        hasWater: true,
        hasElectricity: true,
        hasSecurity: true,
        hasWifi: true,
        images: [],
        agentName: createdAgents[3].name,
        agentPhone: createdAgents[3].phone || "",
        agentWhatsapp: createdAgents[3].phone || "",
        status: "approved" as const,
      },
      {
        userId: createdAgents[3].id,
        title: "Shop Space in Marché Central",
        description: "High-traffic retail location in the Central Market area. Perfect for boutique, electronics store, or any retail business. Excellent foot traffic guaranteed.",
        category: "commercial" as const,
        listingType: "rent" as const,
        price: "350000",
        city: "Yaoundé",
        area: "Marché Central",
        bedrooms: null,
        bathrooms: 1,
        isFurnished: false,
        hasParking: false,
        hasWater: true,
        hasElectricity: true,
        hasSecurity: true,
        hasWifi: false,
        images: [],
        agentName: createdAgents[3].name,
        agentPhone: createdAgents[3].phone || "",
        agentWhatsapp: createdAgents[3].phone || "",
        status: "approved" as const,
      },
      {
        userId: createdAgents[3].id,
        title: "Warehouse for Lease in Ndokoti",
        description: "Large warehouse space suitable for storage or light manufacturing. Easy truck access, loading dock, and 24/7 security. Flexible lease terms available.",
        category: "commercial" as const,
        listingType: "lease" as const,
        price: "600000",
        city: "Douala",
        area: "Ndokoti",
        bedrooms: null,
        bathrooms: 1,
        isFurnished: false,
        hasParking: true,
        hasWater: true,
        hasElectricity: true,
        hasSecurity: true,
        hasWifi: false,
        images: [],
        agentName: createdAgents[3].name,
        agentPhone: createdAgents[3].phone || "",
        agentWhatsapp: createdAgents[3].phone || "",
        status: "approved" as const,
      },
      // Land
      {
        userId: createdAgents[4].id,
        title: "Beachfront Land in Kribi - 1000 sqm",
        description: "Rare opportunity! Prime beachfront property perfect for hotel development or private beach house. Clear title, ready for construction. Direct beach access.",
        category: "land" as const,
        listingType: "sale" as const,
        price: "75000000",
        city: "Kribi",
        area: "Beach Road",
        bedrooms: null,
        bathrooms: null,
        isFurnished: false,
        hasParking: false,
        hasWater: false,
        hasElectricity: false,
        hasSecurity: false,
        hasWifi: false,
        images: [],
        agentName: createdAgents[4].name,
        agentPhone: createdAgents[4].phone || "",
        agentWhatsapp: createdAgents[4].phone || "",
        status: "approved" as const,
      },
      {
        userId: createdAgents[4].id,
        title: "Residential Plot in Nyom - 500 sqm",
        description: "Well-positioned residential plot in developing area of Yaoundé. All utilities nearby. Ideal for building your dream home. Title deed available.",
        category: "land" as const,
        listingType: "sale" as const,
        price: "15000000",
        city: "Yaoundé",
        area: "Nyom",
        bedrooms: null,
        bathrooms: null,
        isFurnished: false,
        hasParking: false,
        hasWater: false,
        hasElectricity: true,
        hasSecurity: false,
        hasWifi: false,
        images: [],
        agentName: createdAgents[4].name,
        agentPhone: createdAgents[4].phone || "",
        agentWhatsapp: createdAgents[4].phone || "",
        status: "approved" as const,
      },
      {
        userId: createdAgents[4].id,
        title: "Commercial Land in Limbe - 2000 sqm",
        description: "Strategic commercial plot on main road. Perfect for shopping center, hotel, or mixed-use development. High visibility location with growing area.",
        category: "land" as const,
        listingType: "sale" as const,
        price: "120000000",
        city: "Limbe",
        area: "Mile 4",
        bedrooms: null,
        bathrooms: null,
        isFurnished: false,
        hasParking: false,
        hasWater: true,
        hasElectricity: true,
        hasSecurity: false,
        hasWifi: false,
        images: [],
        agentName: createdAgents[4].name,
        agentPhone: createdAgents[4].phone || "",
        agentWhatsapp: createdAgents[4].phone || "",
        status: "approved" as const,
      },
      // Short Stay
      {
        userId: createdAgents[0].id,
        title: "Luxury Guest House in Limbe - Ocean View",
        description: "Beautiful guest house with 6 rooms, each with ocean view. Restaurant on-site, pool, and private beach access. Perfect for tourists visiting Mount Cameroon region.",
        category: "short_stay" as const,
        listingType: "short_stay" as const,
        price: "35000",
        city: "Limbe",
        area: "Down Beach",
        bedrooms: 6,
        bathrooms: 6,
        isFurnished: true,
        hasParking: true,
        hasWater: true,
        hasElectricity: true,
        hasSecurity: true,
        hasWifi: true,
        images: [],
        agentName: createdAgents[0].name,
        agentPhone: createdAgents[0].phone || "",
        agentWhatsapp: createdAgents[0].phone || "",
        status: "approved" as const,
      },
      {
        userId: createdAgents[1].id,
        title: "Business Hotel in Akwa - Daily Rates",
        description: "Modern hotel perfect for business travelers. 20 rooms available with AC, TV, and workspace. Conference room available. Airport pickup can be arranged.",
        category: "short_stay" as const,
        listingType: "short_stay" as const,
        price: "25000",
        city: "Douala",
        area: "Akwa",
        bedrooms: 20,
        bathrooms: 20,
        isFurnished: true,
        hasParking: true,
        hasWater: true,
        hasElectricity: true,
        hasSecurity: true,
        hasWifi: true,
        images: [],
        agentName: createdAgents[1].name,
        agentPhone: createdAgents[1].phone || "",
        agentWhatsapp: createdAgents[1].phone || "",
        status: "approved" as const,
      },
      {
        userId: createdAgents[2].id,
        title: "Beach Resort Kribi - All Inclusive",
        description: "Premium beach resort with 12 bungalows. All-inclusive packages available. Water sports, restaurant, bar, and spa services. The perfect getaway destination.",
        category: "short_stay" as const,
        listingType: "short_stay" as const,
        price: "75000",
        city: "Kribi",
        area: "Grand Batanga",
        bedrooms: 12,
        bathrooms: 12,
        isFurnished: true,
        hasParking: true,
        hasWater: true,
        hasElectricity: true,
        hasSecurity: true,
        hasWifi: true,
        images: [],
        agentName: createdAgents[2].name,
        agentPhone: createdAgents[2].phone || "",
        agentWhatsapp: createdAgents[2].phone || "",
        status: "approved" as const,
      },
      // More variety
      {
        userId: createdAgents[3].id,
        title: "Penthouse Apartment in Bonanjo",
        description: "Exclusive penthouse with panoramic views of Douala. 3 bedrooms, rooftop terrace, smart home features. Building has gym, pool, and concierge service.",
        category: "residential" as const,
        listingType: "rent" as const,
        price: "950000",
        city: "Douala",
        area: "Bonanjo",
        bedrooms: 3,
        bathrooms: 2,
        isFurnished: true,
        hasParking: true,
        hasWater: true,
        hasElectricity: true,
        hasSecurity: true,
        hasWifi: true,
        images: [],
        agentName: createdAgents[3].name,
        agentPhone: createdAgents[3].phone || "",
        agentWhatsapp: createdAgents[3].phone || "",
        status: "approved" as const,
      },
      {
        userId: createdAgents[4].id,
        title: "Family House in Biyem-Assi",
        description: "Comfortable 4-bedroom family home in peaceful neighborhood. Large living area, modern kitchen, garden with fruit trees. Close to schools and supermarkets.",
        category: "residential" as const,
        listingType: "rent" as const,
        price: "280000",
        city: "Yaoundé",
        area: "Biyem-Assi",
        bedrooms: 4,
        bathrooms: 2,
        isFurnished: false,
        hasParking: true,
        hasWater: true,
        hasElectricity: true,
        hasSecurity: false,
        hasWifi: false,
        images: [],
        agentName: createdAgents[4].name,
        agentPhone: createdAgents[4].phone || "",
        agentWhatsapp: createdAgents[4].phone || "",
        status: "approved" as const,
      },
      {
        userId: createdAgents[0].id,
        title: "Restaurant Space for Lease - Bastos",
        description: "Turn-key restaurant space in expat area. Fully equipped kitchen, 50-seat dining area, outdoor terrace. Previously successful restaurant location.",
        category: "commercial" as const,
        listingType: "lease" as const,
        price: "1200000",
        city: "Yaoundé",
        area: "Bastos",
        bedrooms: null,
        bathrooms: 2,
        isFurnished: true,
        hasParking: true,
        hasWater: true,
        hasElectricity: true,
        hasSecurity: true,
        hasWifi: true,
        images: [],
        agentName: createdAgents[0].name,
        agentPhone: createdAgents[0].phone || "",
        agentWhatsapp: createdAgents[0].phone || "",
        status: "approved" as const,
      },
    ];

    await db.insert(listings).values(sampleListings);

    return NextResponse.json({
      message: "Seed data created successfully!",
      admin: { email: "samuel.adesanya1love@gmail.com", password: "admin123" },
      agents: demoAgents.map(a => ({ email: a.email, password: "agent123" })),
      listingsCreated: sampleListings.length,
    });
  } catch (error) {
    console.error("Seed error:", error);
    return NextResponse.json(
      { error: "Internal server error" },
      { status: 500 }
    );
  }
}
